language: node_js
node_js:
  - 5.7
install:
  - sudo curl https://install.meteor.com/ | /bin/sh
  - npm install -g coffee-script spacejam@1.6.2-rc.1
script:
  - spacejam test-packages --once --driver-package=test-server-tests-in-console-once ./ --settings ./dummy-settings.json
