language: node_js
node_js:
  - 5.7
install:
  - sudo curl https://install.meteor.com/ | /bin/sh
script:
  - spacejam test-packages --driver-package=practicalmeteor:mocha-console-runner ./ --settings ./dummy-settings.json
