language: node_js
node_js:
  - 5.7
install:
  - sudo curl https://install.meteor.com/ | /bin/sh
  - npm install -g spacejam
script:
  - spacejam test-packages --driver-package=practicalmeteor:mocha-console-reporter ./ --settings ./dummy-settings.json
